spring:
  datasource:
    # ğŸ“ Adresse bdd PostgreSQL
    # mlm_bdd = nom bdd
    url: jdbc:postgresql://localhost:5433/mlm_bdd
    username: postgres
    password: root
    # ğŸš— Driver JDBC pour PostgreSQL (permet Ã  Java de parler avec PostgreSQL)
    driver-class-name: org.postgresql.Driver

  flyway:
    # âœ… Active Flyway au dÃ©marrage de l'application
    # Flyway va chercher et exÃ©cuter les scripts SQL
    enabled: true
    # Permet de rajouter des Flyway
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
      # Afficher les logs de Hibernate
    show-sql: true

logging:
  # Je sais pas trop
  level:
    org.flywaydb: DEBUG